
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metrics-server
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://kubernetes-sigs.github.io/metrics-server/
    targetRevision: 3.8.4
    chart: metrics-server
    helm:
      version: v3
      releaseName: metrics-server
      passCredentials: false
      parameters:
        - name: "image.tag"
          value: v0.6.2
      values: |
        defaultArgs:
        - --cert-dir=/tmp
        - --kubelet-preferred-address-types=InternalIP,ExternalIP,Hostname
        - --kubelet-use-node-status-port
        - --metric-resolution=15s
        - --kubelet-insecure-tls
      valueFiles:
  #    values file can be stored in a separate git repository
  # - $values/charts/prometheus/values.yaml
  # - repoURL: 'https://git.example.com/org/value-files.git'
  #   targetRevision: dev
  #   ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - Validate=true
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true